[package]
name = "infra_repository_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }
config = { path = "../../config" }

anyhow = "1.0.58"
async-trait = "0.1.56"
serde = "1.0.140"
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "mysql", "chrono"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
chrono = "0.4.19"
