[package]
name = "seichi-game-api"
version = "0.1.0"
edition = "2021"

[dependencies]
pbjson-types = "0.3.0"
prost = "0.10.1"
tokio = { version = "1.18.0", features = ["rt-multi-thread"] }
tonic = { version = "0.7.1", features = ["compression"] }
