[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
chrono = "0.4.19"
serde = "1.0.140"
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
