[package]
name = "seichi-game-api"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
config = { path = "../config" }
infra_grpc = { path = "../infra/grpc" }
infra_repository_impl = { path = "../infra/repository_impl" }

anyhow = "1.0.58"
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
tonic = { version = "0.7.2", features = ["compression"] }
