[package]
name = "seichi-game-api"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
config = { path = "../config" }
infra_grpc = { path = "../infra/grpc" }
infra_repository_impl = { path = "../infra/repository_impl" }

anyhow = "1.0.68"
tokio = { version = "1.25.0", features = ["rt-multi-thread"] }
tonic = { version = "0.8.3", features = ["gzip"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"
tower-http = { version = "0.4.0", features = ["trace"] }
