[package]
name = "infra_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }

anyhow = "1.0.66"
async-trait = "0.1.58"
log = "0.4.17"
pbjson-types = "0.3.2"
prost = "0.11.2"
serde = "1.0.147"
tonic = { version = "0.7.2", features = ["compression"] }
