[package]
name = "infra_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
# pbjson-types, prost, tonicは `<= 1.0.0` の範囲でminor versionが上がった場合全て一緒にbumpすること。buf.gen.yamlの
# バージョンをあげることも忘れずに。

domain = { path = "../../domain" }

anyhow = "1.0.69"
async-trait = "0.1.65"
log = "0.4.17"
pbjson-types = "0.5.1"
prost = "0.11.8"
serde = "1.0.152"
tonic = { version = "0.9.1", features = ["gzip"] }
